name: Docker Build & Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "PORT=3000" >> .env
          echo "STRIPE_SECRET_KEY=sk_test_51QT6CHAs4cEkYxhecF1lP3ZsiQC7H3mgGK1nlv0VOPkGuOLUWBMqTO83eC5E1BSvhchgvyCYnjhMR4WgSyuXkJv100lm4twQAO" >> .env
          echo "STRIPE_SIGNATURE=whsec_3kfIgTkQqJ0iv9ecFR1R3CSAhcczMtz2" >> .env
          echo "BASE_URL=https://back.ticktopia.shop/api" >> .env
          echo "GOOGLE_APPLICATION_CREDENTIALS=./thinking-land-459213-k5-ad5821b1ca9a.json" >> .env
          echo "FRONTEND_URL=http://localhost:8080" >> .env



          

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: elkofix
          password: dckr_pat_yHlywi4bXYAtC5o9Et0OlvEBV8E

      - name: Build Docker Image
        run: |
          docker build -t elkofix/ticktopia:latest .

      - name: Push Docker Image
        run: |
          docker push elkofix/ticktopia:latest

      - name: Delete docker container and update image
        run: |
          chmod 400 ./backend-ticktopia.pem

          ssh -o StrictHostKeyChecking=no -i ./backend-ticktopia.pem ubuntu@54.209.246.34 << 'EOF'
          #!/bin/bash
          set -e
          docker pull elkofix/ticktopia:latest
          docker stop ticktopia-backend
          docker rm ticktopia-backend
          docker image prune -f
          docker rmi elkofix/ticktopia:latest || true
          docker run -d -p 1337:3000 --name ticktopia-backend elkofix/ticktopia:latest
