name: Run Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: |
          npx nyc --reporter=text-summary npm test

      - name: Check coverage threshold
        run: |
          COVERAGE=$(npx nyc report --reporter=text-summary | grep "Statements" | awk '{print $2}' | sed 's/%//')
          echo "Coverage is $COVERAGE%"
          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
            echo "❌ Coverage below 80%."
            exit 1
          else
            echo "✅ Coverage acceptable."
          fi
